name: Build and Push to ECR

on:
  push:
    tags:
      - '*'   # her tag geldiğinde çalışır
    branches:
      - main

env:
  AWS_REGION: us-east-1         # kendi bölgeni yaz
  ECR_REPOSITORY: devicepark  # ECR repository adın
  PROJECT_NAME: allocation-api     # image için temel isim

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}/${{ env.PROJECT_NAME }}:$IMAGE_TAG
          
          echo "Building image: $IMAGE_URI"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
