name: Build and Push to Public ECR

on:
  push:
    tags:
      - '*'   # her tag geldiğinde çalışır

env:
  AWS_REGION: us-east-1
  PUBLIC_ECR_REPOSITORY: public.ecr.aws/devicepark/allocation-api
  PROJECT_NAME: allocation-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Public ECR
        run: |
          aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ env.PUBLIC_ECR_REPOSITORY }}

      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          IMAGE_URI=${{ env.PUBLIC_ECR_REPOSITORY }}:${IMAGE_TAG}
          
          echo "Building image: $IMAGE_URI"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
